services:
  production-server:
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-4408}
      - ACCESS_KEYS=${ACCESS_KEYS:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://localhost:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
    ports:
      - "${PORT:-4408}:4408"
    build:
      dockerfile: Dockerfile
      context: .
